### ISSUE TITLE
When mounting the filesystem stdout is cluttered with "no tables in statement !" lines

### ISSUE THREAD

**Issue by denizzzka** [StrumentiResistenti/Tagsistant#10]
on Debian, same problem as described here:
https://www.tagsistant.net/kunena/0-6-feedback/74-not-stable-enough?start=30#161

```
  Tagsistant (tagfs) v.0.8.2 (codename: Athens) 
  Build: 576.20150726.000003 FUSE_USE_VERSION: 26
```

**Comment by StrumentiResistenti** [comment]
Short answer: This is internal to libdbi and Tagsistant can't do too much to remove the clutter.

Long answer: Before calling `dbi_conn_query()` it is advisable to call `dbi_conn_ping()` to ensure that the DBI connection is still open. Seems like calling this function triggers the message when using the SQLite DBD driver. I've tried to avoid calling `dbi_conn_ping()` on SQLite, supposing that not having a real TCP/IP or UNIX pipe connection with a server makes pinging useless, but I've found that sometimes the DBI handle was no longer usable, without any predictability. So I've reintroduced the call to `dbi_conn_ping()`.

However, if you think I've overlooked something, please feel free to provide a patch or some insight on how to avoid this clutter. Thank you.

**Comment by denizzzka** [comment]
Ok.

I just think that this is bad idea to use DBI rather than pure libsqlite3. No one isn't changes DB engine without big researching due to SQL DBs is really are different. Biggest reason what it is avalable many SQL DB is different approach to the implementation of various things inside of them, which is reflected in the differences in the syntax of queries, for example.

All this old marketing ploy.

**Comment by StrumentiResistenti** [comment]
Tagsistant supports two backends: SQLite and MySQL. And I would like to add other RDBMS. Using DBI makes this simpler than using N different APIs.

I do not assume that Tagsistant users will convert SQLite repositories to MySQL or vice versa. I just assume that some users will use SQLite for their repositories and others will use MySQL, depending on their personal preferences and considerations or the context they will use Tagsistant in.

**Comment by denizzzka** [comment]
By getting rid of this unnecessary universality it helps to avoid this error, and some others too.

**Comment by StrumentiResistenti** [comment]
It is not "unnecessary universality": without it I would be forced to develop a different backend for each supported RDMBS and I would just not do this. It's already difficult to find the time to code new features and fix bugs, the perspective of doing this in two or more different APIs would just make me give up.

**Comment by StrumentiResistenti** [comment]
Now you may ask: why supporting several RDBMS is interesting? Why not focus on one product and use just that, squeezing all the potential it offers?

Many people reported the use of Tagsistant with SQLite on cloud storage. They keep the repository in a folder synchronized on-line. Using MySQL would not allow this. Others reported to use Tagsistant with MySQL for performance reasons, because the repository is exported to several users over the net by a Samba server. SQLite would not fit this scenario.

I agree on one point: it's not very probable that a SQLite repository gets migrated to MySQL or vice versa. But different RDBMS fit different environments and different requirements. I would like to add support for others, like Postgres and Oracle, not to drop one in MySQL or SQLite just to directly use its API.

**Comment by mrmodolo** [comment]
Hi!

I run tagsistant with the following command:

/usr/bin/tagsistant ~/files &> /dev/null

No more "no tables in statement !"
