### ISSUE TITLE
deduplicate before copy

### ISSUE THREAD

**Issue by milahu** [StrumentiResistenti/Tagsistant#14]
tagsistant-0.8.1a stores files, before looking for duplicates.
even when i copy inside a tagsistant mount.

this behavior is bad because:

1. its a waste of time.

2. it pollutes my storage device, probably with sensitive data, which are not wiped (= pseudo securely removed by overwriting).

3. it decreases the lifetime of my storage device, especially with flash memory in solid state drives or USB flash drives.

please fix this, before i do ; )

edit:

workaround 1, for copying inside tsa_mnt:
use hardlink: `ln store/tag1/\@/file store/tag2/\@/`
instead of copy: `cp store/tag1/\@/file store/tag2/\@/`

workaround 2, for copying from outside of tsa_mnt:
`cp ../file store/tag1/tag2/\@/`
result: file stored once and tagged twice.

**Comment by StrumentiResistenti** [comment]
If you want to make a link inside Tagsistant you can already do this. 

If you want to change the tag set of an object, just move it from a location to another:

    $ mv mpoint/store/t1/t2/@/file.txt mpoint/store/t3/@

This will remove tags t1 and t2 and add tag t3 to file.txt. More info [here](http://www.tagsistant.net/documents-about-tagsistant/0-8-1-howto?showall=&start=8). So if you don't want to create an avoidable copy of file already managed by Tagsistant, you actually can.

Preventing duplication while copying from _outside_ Tagsistant is simply impossible. Don't forget that Tagsistant is filesystem agnostic: it makes no assumption on the underlying filesystem. That's why it can be used through a remote file server like Samba or NFS.

When you do a:

    $ cp some/where/outside/file.txt mpoint/store/t1/@/

what Tagsistant actually sees is:

    1 x tagsistant_open("/store/t1/@/file.txt", ...)
    n x tagsistant_write("/store/t1/@/file.txt", ...)
    1 x tagsistant_flush("/store/t1/@/file.txt", ...)
    1 x tagsistant_release("/store/t1/@/file.txt", ...)

It can't trap the original file location, which BTW could even not exist at all, like in the case of an on-the-fly generated picture, output by a manipulation tool, for example.
