### ISSUE TITLE
Permission denied for root

### ISSUE THREAD

**Issue by milahu** [StrumentiResistenti/Tagsistant#18]
> $ tagsistant tsa_rep tsa_mnt
> $ sudo stat tsa_mnt
> stat: cannot stat 'tsa_mnt': Permission denied

this does not make sense to me...

**Comment by StrumentiResistenti** [comment]
Did you added the line "user_allow_other" to /etc/fuse.conf?

**Comment by milahu** [comment]
no. no.

now i have, and it works. : )

i'm still a bit confused, that a user can hide files from root...
maybe fuse introduces a new user, with unlimited access:
superroot aka laplacesdaemon... ; )

thanks!

**Comment by StrumentiResistenti** [comment]
Exactly as you guessed, it's a FUSE limitation and must be circumvented with a FUSE option. :)

Since FUSE is often used to create "personal" filesystem (like SSHFS which originated FUSE itself) the author thought it was a good idea to prevent root from accessing regular user files, unless explicitly allowed to.
