### ISSUE TITLE
Only one file permited

### ISSUE THREAD

**Issue by thiagokrieck** [StrumentiResistenti/Tagsistant#19]
After installing Tagsistant on a linux mint vm I can add just one file to the repository but the second one get a "could not find file or directory" message on copy. I tried to recreate the repository but the same problems occurs. 

I the archive dir the name of the second file is there, but without it's contents (like as it was created by a touch command, but it was not created that way by me)

**Comment by StrumentiResistenti** [comment]
Hi thiagokrieck, this is a known bug related to SQLite and newer versions of libDBI: getting the last inserted sequence number is no longer possible and the query always returns 1. That's why only the first object is properly created.

The bug does not involve MySQL so please consider using it in place of SQLite, while I look for a fix or a workaround. 

Thanks.

**Comment by thiagokrieck** [comment]
Awesome, thanks. By the way, your product is amazing.

**Comment by StrumentiResistenti** [comment]
This is just a dirt workaround to avoid requesting the last inserted row id. By locking a mutex just before inserting the new record in the objects table, I'm able to always get the right inode. This of course comes at the price of a mutex lock and requires getting the max(inode) which may not be optimal when the table grows too much.
