### ISSUE TITLE
Filesystem not ready for programs run shortly after tagsistant returns

### ISSUE THREAD

**Issue by AdrianSchurz** [StrumentiResistenti/Tagsistant#20]
Óla compadres,

great piece of work, solves a hell of a lot of problems I had for so long rather cleanly!

I am, though, frequently using a pretty old dual core/1GB ram thinkpad (64bit Arch Linux, up to date). When tagsistant is run at startup (first line of .xinitrc) my window manager (last line of .xinitrc) fails about 50% of the time when trying to load a wallpaper residing inside my tagsistant mount. Restarting it then works every time, leading me to suspect that there is a delay between tagsistant returning from its invokation in the init script and the filesystem being fully set up.

Are there remedies for that (other than some calling sleep or polling the filesystem until it works, bleurgh!)? And is this intended behaviour?

Best regards,

Adrian

**Comment by StrumentiResistenti** [comment]
Hi Adrian, thank you very much for your appreciacion!

I suppose your problem comes from the delay between the start of tagsistant and the fork it does to go into background. I don't think there's something "to fix" here on tagsistant side, you just have to
wait for the filesystem to be properly mounted. I would suggest a poll for the existence of specific tagsistant directories, like store/ or tags/:

    `while [ ! -d $MPOINT/stores/ ]; do sleep 1; done`

Of course this is rather simplistic, you'll probably want a timeout too or some maximal iteration threshold to reach, to avoid endless looping.

Another way you could try is to start tagsistant in foreground mode and send it background with the shell, like in:

    `$ tagsistant -f <repo> <mpoint> 1>/dev/null 2>/dev/null &`

This should do the trick. The fork tagsistant does is just to avoid output redirection when mounting it by hand on a running shell.

Hope this helps. ;)

**Comment by AdrianSchurz** [comment]
Oh hi, thanks for the swift answer.
The second one does not work, the first one I have not tried yet as there isn't really a way it won't work :D. I was just trying to avoid that approach but it isn't too big a deal either. Would you be so kind to describe how the second one would work if it did. Does tagsistant detect somehow that it's output is redirected or is the "&" (which I fuzzily remember as simply detaching the process from its parent) the thing that makes it work. If so, does tagsistant detect this and decide there is no fork necessary? Just curious because I still suffer from quite a few blind spots in regards to how linux processes and shells work.

Cheers
