### ISSUE TITLE
Suggestion: symlink in every /store/... folder to the respective folder under /tags/...

### ISSUE THREAD

**Issue by conrad-heimbold** [StrumentiResistenti/Tagsistant#24]
Does anybody of you have an idea how we can make tagsistant more user-friendly? I often make the tags (aka folders) somewhere deep down in /store when I already have got the file (that should be tagged) in the clipboard. Sometimes, I notice afterwards, that another tag would be more appropriate. But then, unfortunately, I have to go all the folders up again until $MOUNTPOINT/tags/... to delete it again. It also seems inconsistent to me, that creating tags can be done anywhere (also deep down!) inside of $MOUNTPOINT/store/... without affecting any file, but deleting tags aka folders can only be done at $MOUNTPOINT/tags/, and indeed affect lots of files if done under $MOUNTPOINT/store.  

I also don't know, if and how you can use mv to rename a tag. Is this possible? 

Would it be maybe possible to automatically make a symlink-file in every folder under /store to the respective folder under /tags? 

An example: 
```sh
$ tagsistant /home/user_name/tagged_files
$ cd ~/tagged_files/store/entertainment:/media_type/music/audio:/genre
# (games are also a form of entertainment, that's why there's 
# another folder named games)
$ ls -l
... rock 
... jazz 
... pop
... "rHyThM_&_bLuEs"
# Now I want to rename rHyThM_&_bLuEs to rhythm_&_blues. 
# Unfortunately, direct renaming is not possible, so I would have 
# to delete the tag first, and then create a new tag with the correct name. 
# So I have to: 
$ cd ../../../../../../tags/audio:/genre
$ rmdir "rHyThM_&_bLuEs"
$ mkdir "rhythm_&_blues"
```

That is extremely uncomfortable! Just for renaming the tag??? Couldn't that be done in some way shorter? The cd ../../../../../../tags/audio:/genre takes REALLY a lot of time when doing the whole thing in a graphical file manager (but also in the terminal). Of course, you could make some shurtcuts manually, or cd ~/tagged_files/tags/audio:/genre , but in my opinion, programs should be user-friendly out of the box. 

So my suggestion is: What if you would also see an automatically created symlink like the following when doing ls, indifferent from the folder you are at the moment under $MOUNTPOINT/store?
```sh
$ ls -l 
... rock 
... jazz 
... "rHyThM_&_bLuEs"
... tags -> /home/user_name/tagged_files/tags/audio:/genre/ 
```
(The last line is the symlink)

so you would just have to
```sh
$ cd tags
$ rmdir "rHyThM_&_bLuEs"
$ mkdir "rhythm_&_blues"
```

Could you implement such a feature? 
It would be even more easier to handle tags, if deleting folders under /store would only delete the tags (aka folders), but not the files. Deleting files can still be done when going to /store/ALL/@ or to /archive. That would however be a much more radical solution...

As far as I know, people more often rename folders or create new folders, than deleting files. 

Any other suggestions welcome!

**Comment by StrumentiResistenti** [comment]
Just rename the tag.

```
$ tagsistant ~/mpoint
$ mkdir ~/mpoint/tags/oldname
$ mv ~/mpoint/tags/oldname/ ~/mpoint/tags/newname
$ ll ~/mpoint/tags/
total 12K
drwxr-xr-x 2 user user 4,0K nov 18 10:51 .
drwxr-xr-x 2 user user 4,0K nov 18 10:51 ..
drwxr-xr-x 2 user user 4,0K nov 18 10:51 newname
$ ll ~/mpoint/store/
total 36K
drwxr-xr-x 1 user user 4,0K nov 18 10:51 -
drwxr-xr-x 2 user user 4,0K nov 18 10:51 .
drwxr-xr-x 2 user user 4,0K nov 18 10:51 ..
drwxr-xr-x 3 user user 4,0K nov 18 10:51 {
drwxr-xr-x 2 user user 4,0K nov 18 10:51 @
drwxr-xr-x 2 user user 4,0K nov 18 10:51 @@
drwxr-xr-x 1 user user 4,0K nov 18 10:51 +
drwxr-xr-x 2 user user 4,0K nov 18 10:51 ALL 
drwxr-xr-x 2 user user 4,0K nov 18 10:51 newname
$
```

However, writing this post, I've just noticed that doing the same on a triple tag leads to an error. If you change the value, Tagsistant returns with no error, but the value is not changed. If you change the key or the namespace, a "No such file or directory" error is returned. Fortunately, you can use the "tag merging" approach to solve this issue. More information here: http://www.tagsistant.net/documents-about-tagsistant/0-8-1-howto?showall=&start=9

And by the way I can't prevent file elimination when you delete a tag inside store/. It's not Tagsistant that does this, but your file manager or command line utility. If you delete "store/tagX/" from a file manager, it will first start by deleting its contents. Obviously Tagsistant will list the whole repository as a content, because of its own operational model. Literally, there's nothing I can do to prevent a recursive erase. That's why I've created tags/. Otherwise deleting a tag would have been impossible.

I hope this makes clear that's not a limitation of Tagsistant, but a consequence of introducing a non hierarchical behavior (tags can reverse their parent-child relations in a path) inside a hierarchical model: the traditional POSIX filesystem. Some compromises had to be done.

I'm thinking to write a (graphical or command line) tool to help manage tagging. This would prevent accidental data loss. Do you think this would make Tagsistant more user friendly?

**Comment by conrad-heimbold** [comment]
Wouldn't it be easier to just make that symlink automatically inside of every /store folder? That would be a quick fix, and for the future we can try to fix mv for triple tags!

**Comment by conrad-heimbold** [comment]
So e.g.: 
```sh
$ cd ~/tagged_files/store/audio:/
$ ls -al
<file> genre
<file> artist
<link> .tags -> ~/tagged_files/tags/audio:/
$ cd genre
$ ls -l
<file> rock
<file> pop
<link> .tags -> ~/tagged_files/tags/audio:/genre
```
Those symlinks named ".tags" would then be created automatically by tagsistant

**Comment by StrumentiResistenti** [comment]
If I understand what you're proposing, the symlink would point to the current tag but inside the tags/ main dir. So, provided that <mpoint> is the current mountpoint, in store/tag1/ a symlink named .tags would point to <mpoint>/tags/tag1.

How would you use the symlink then? Please, list the commands you would run involving the symlink.

**Comment by conrad-heimbold** [comment]
I already listed the commands I would run involving the symlink and the following commands in the top post, the only difference between my top post and the last comment is: 
• in the top post, the symlink is a regular file
• in the last comment, the symlink is a hidden file, because it starts with an dot .

**Comment by StrumentiResistenti** [comment]
If this is the list you're referring to:

```
$ cd tags
$ rmdir "rHyThM_&_bLuEs"
$ mkdir "rhythm_&_blues"
```

I would just note that you can't "cd" inside a symlink or a regular file. You would instead:

```
$ cd `cat tags`
```

which is not intuitive and not very practical with a file manager.

**Comment by conrad-heimbold** [comment]
Unfortunately, you are right: If you follow a symlink that points to a folder, the contents of the linked folder get actually remounted under the symlink, you do not change your location inside the filesystem. So my suggestion won't work. Or is there some other kind of link, that points actually to another folder and does not remount it beneath itself?

**Comment by StrumentiResistenti** [comment]
Well, I'm actually half-right only. You can't "cd" inside a file. But if you symlink a directory, you can "cd" inside the symlink, so your proposal could be implemented as a symlink. However I don't think it is really needed. 

I mean: a tag is actually an object inside the repository, being it simple or triple. Its name is just a way we humans can interact with the tag and recall it in our queries. So if you start tagging a set of files as "rhythm_&_blues" and later decide that "rhythm_and_blues" is a better name, just go on with "rhythm_&_blues". When your're done, rename the tag once. All your files will than be available as "rhythm_and_blues". Or open another terminal, do the rename, close it and go on with tagging in the previous terminal (or file manager).

I would instead be more keen to fixing the rename bug on triple tags, than adding another conventional trick. Too many conventions may overload a software and make it unusable.

There's already a very similar convention trick to list the tags applied to an object: add the ".tags" suffix to its name. This works for files, symlinks and directories too! In the last case it is very disputable because, if `store/t1/@/dir` is a directory, `store/t1/@/dir.tags` is then a file! I wasn't able to come up with a better convention than to append a suffix to the object name. Moreover, there's no hint at all that this trick is available, unless you read all the documentation. But as I said previously, some compromises had to be made.

I hope I haven't overlooked any of your requirements. Thanks.

**Comment by conrad-heimbold** [comment]
Thanks for your fast answer! Implementing the mv command properly is definitely the better idea than creating some new conventions.

**Comment by StrumentiResistenti** [comment]
I've fixed the triple tag renaming. Valid examples follow:

```
$ mv store/ns:/key/eq/val store/ns:/key/eq/newval # value rename
$ mv store/ns:/key/ store/ns:/newkey              # key rename
$ mv store/ns: store/new_ns:                      # namespace rename
```
Invalid examples are:
```
$ mv store/ns:/key/eq/val store/ns:/newkey/eq/val   # if newkey does not exist
$ mv store/ns:/key/eq/val store/new_ns:/key/eq/val  # if new_ns: and new_ns:/key/eq/ do not exist
```
The key and the namespace can be renamed only if the destination exists:
```
$ mkdir store/ns:/k5
$ mv store/ns\:/k4/eq/v2/ store/ns\:/k5/eq/v2
```
