### ISSUE TITLE
What about trackers?

### ISSUE THREAD

**Issue by tjfwalker** [StrumentiResistenti/Tagsistant#3]
@StrumentiResistenti can you explain to me how Tagsistant works with things that are usually placed inside of directories to track the contents of those directories, like `.git` folder for Git repos, `.sync` for Bittorrent Sync folder, et cetera? How would I manage a Git project if there is no dir for it? Can `.git` instead be setup to track changes to a certain tag, or what?

**Comment by StrumentiResistenti** [comment]
You can create a directory for your project and tag the directory (for example "store/tag1/tag2/@/project/") and then put all your files inside it. The "project" directory itself is tagged, while the contained files are not. The content of "project" follows the same semantic rules you expect on a traditional hierarchical filesystem.

**Comment by denizzzka** [comment]
What if file in the directory will be tagged?
What if subdirectory in this directory will be tagged?

**Comment by StrumentiResistenti** [comment]
Objects get tagged by copying or linking them inside `mountpoint/store/.../@/`. Only the objects directly included in that path are tagged. So if you:

`$ cp somefile.txt mountpoint/store/tag/@/`

the file `somefile.txt` is tagged. If you create a directory like this:

`$ mkdir mountpoint/store/tag/@/newdir`

the `newdir` directory is tagged. But if you copy something inside `newdir`, it does not get tagged and that makes a lot of sense since when you look for files matching a query, like in:

`$ ls mountpoint/store/tag/@`

the last thing you want is to have the whole content of `newdir` rolled out, file after file. That's why Tagsistant will list just `newdir` and if you're interested you can list its content by:

`$ ls mountpoint/store/tag/@/newdir/`

All that said, the best way to tag a Git repository is creating a directory for it under `mountpoint/store/.../@` and put all its contents inside that directory. 

However, my personal opinion is that Tagsistant is not the right tool to store Git repositories (unless you have thousands of repositories to catalogue). Tagsistant was created to store collections of self-standing objects like pictures, texts, audio samples and music, data samples and things like this. A Git repository is a structured set of files that does not fit Tagsistant storage model and needs a wrapping directory to be saved in. A dedicated directory in a traditional filesystem is more appropriate. But that's just my opinion.

**Comment by JoshOrndorff** [comment]
The original question is answered thoroughly. Should this issue be closed?
